language: node_js

branches:
  only:
  - master

node_js:
  - 8
  - 12

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npm t && codecov
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
    - stage: gh-pages
        script: npm run docs
        deploy:
          provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
          local_dir: docs
          on:
            branch: master

