language: node_js

branches:
  only:
  - master

node_js:
  - 8
  - 12

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: codecov
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

